# Generated by Django 3.2.4 on 2022-05-24 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamos'], [2, 'sugerencias'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estado_cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20, null=True)),
                ('montoapagar', models.IntegerField()),
                ('morosidad', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='notificaciones')),
            ],
        ),
        migrations.CreateModel(
            name='residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('n_departamento', models.IntegerField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estado_cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.area')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.residente')),
            ],
        ),
    ]
