# Generated by Django 3.2.4 on 2022-05-24 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=100000)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='pago_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=100000)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estado_cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.CharField(max_length=10)),
                ('hora_termino', models.CharField(max_length=10)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.area')),
            ],
        ),
    ]
