# Generated by Django 3.2.4 on 2022-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_horario_pago_estado_pago_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='imagen',
            field=models.ImageField(null=True, upload_to='residentes'),
        ),
    ]
