# Generated by Django 3.2.4 on 2022-05-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_area_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_estado',
            name='forma_pago',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pago_reserva',
            name='forma_pago',
            field=models.CharField(max_length=100),
        ),
    ]
