# Generated by Django 3.2.4 on 2022-05-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220524_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_estado',
            name='forma_pago',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pago_reserva',
            name='forma_pago',
            field=models.TextField(null=True),
        ),
    ]
