# Generated by Django 3.2.4 on 2022-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220524_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_estado',
            name='forma_pago',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pago_reserva',
            name='forma_pago',
            field=models.TextField(null=True),
        ),
    ]
