# Generated by Django 3.2.4 on 2022-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220524_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_estado',
            name='forma_pago',
            field=models.TextField(max_length=65532, null=True),
        ),
        migrations.AlterField(
            model_name='pago_reserva',
            name='forma_pago',
            field=models.TextField(max_length=65532, null=True),
        ),
    ]
